# +++++++++++++++++++++++++++++++++++++++++++++++++++++++#
#           CONFIGURATION FOR TETHER PLUGIN
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++#


# CHANCE FOR SUCCESSFUL BINDING
tether_chance: 100

# COOLDOWN BETWEEN BINDING ATTEMPTS *minutes
tether_cooldown_minutes: 7

# MAXIMUM DISTANCE TO INITIATE BINDING
tether_max_distance: 2

# TIME REQUIRED TO BIND A PLAYER *seconds
tether_duration_seconds: 2

# DURATION OF BINDING EFFECT *seconds (separate from debuffs)
tether_effect_duration_seconds: 300

# DISTANCE AT WHICH PLAYER IS TELEPORTED TO BINDER
tether_pull_distance: 50

# PUSH FORCE TOWARDS BINDER
tether_pull_speed: 1.2

# TIME REQUIRED TO UNBIND A PLAYER *seconds
unbind_duration_seconds: 10

# MAX DISTANCE A BOUND PLAYER CAN MOVE FROM BINDER
binding_max_distance: 5

# CHANCE FOR SUCCESSFUL UNBINDING
unbind_chance: 100

# COOLDOWN BETWEEN UNBINDING ATTEMPTS *minutes
unbind_fail_cooldown_minutes: 1

# DEBUFFS
debuffs:
  blindness:
    duration_seconds: 300
    level: 0
  slowness:
    duration_seconds: 300
    level: 0
  weakness:
    duration_seconds: 300
    level: 0