# +++++++++++++++++++++++++++++++++++++++++++++++++++++++#
#           КОНФІГУРАЦІЯ ДО ПЛАГІНА ЗВ'ЯЗУВАННЯ
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++#



# ШАНС НА ВДАЛЕ ЗВ'ЯЗУІВННЯ
tether_chance: 100

# КУЛДАУН МІЖ СПРОБАМИ ЗВ'ЯЗАТИ ЛЮДИНУ *хвилин
tether_cooldown_minutes: 7

# МАКМСИМАЛЬНА ДИСТАНЦІЯ ДЛЯ СПРОБИ ЗВ'ЯЗАТИ ГРАВЦЯ
tether_max_distance: 2

# ЧАС ПОТРІБНИЙ ДЛЯ ЗВ'ЯЗУВАННЯ ГРАВЦЯ
tether_duration_seconds: 2

# ЧАС КОЛИ ГРАВЕЦЬ БУДЕ ПРИВ'ЯЗАНИЙ ДО ЛЮДИНИ *ОКРЕМО ВІД ЕФЕКТІВ*
tether_effect_duration_seconds: 300

# ДИСТАНЦІЯ ПІСЛЯ КОТРОХ ЛЮДИНУ ТЕЛЕПОРТУЄ ДО ЗВ'ЯЗУЮЧОГО
tether_pull_distance: 50

# СИЛА ПІДШТОВХУВАННЯ ГРАЦВЯ ДО ЗВ'ЯЗУЮЧОГО
tether_pull_speed: 1.2

# ЧАС ПОТРІБНИЙ ДЛЯ РОЗВ'ЯЗУВАННЯ ГРАВЦЯ
unbind_duration_seconds: 10

# ДИСТАНЦІЯ НА КОТРУ МОЖЕ ВІДІЙТИ ЗВ'ЯЗАНИЙ ГРАВЕЦЬ
binding_max_distance: 5

# ШАНС НА ВДАЛЕ РОЗВ'ЯЗУВАННЯ
unbind_chance: 100

# КУЛДАУН МІЖ СПРОБАМИ РОЗВ'ЯЗАТИ ЛЮДИНУ *хвилин
unbind_fail_cooldown_minutes: 1

# ЕФЕКТИ *ОБЕРЕЖНО*
debuffs:
  blindness:
    duration_seconds: 300
    level: 0
  slowness:
    duration_seconds: 300
    level: 0
  weakness:
    duration_seconds: 300
    level: 0
